"""drop vocabulary from submission_scores

Revision ID: 9eac39f7a87b
Revises: 8ac011f2b749
Create Date: 2026-08-01 21:53:33.391333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eac39f7a87b'
down_revision: Union[str, Sequence[str], None] = '8ac011f2b749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_scores', 'vocabulary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_scores', sa.Column('vocabulary', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
